from django.urls import path
from . import views

urlpatterns = [ 
    path('home', views.home, name = 'home'),
    path('', views.home, name = 'home'),
    path('pricing', views.pricing, name = 'pricing'),
    path('tabs', views.tabs, name = 'tabs'), 
    path('sign_up', views.signup, name = 'sign_up'),
    path('anchors', views.anchors, name = 'anchors'), 
    path('run_load', views.run_load, name = 'run_load'),
    path('load_anchors/<str:iso3>', views.load_anchors, name = 'load_anchors'),
    path('fishing_activity', views.fishing_activity, name = 'fishing_activity'), 
    path('track_vessel', views.track_vessel, name = 'track_vessel'),
    path('load_driftinglonglines', views.load_driftinglonglines, name = 'load_driftinglonglines'), 
    path('load_fixedgear', views.load_fixedgear, name = 'load_fixedgear'), 
    path('load_squidjigger', views.load_squidjigger, name = 'load_squidjigger'), 
    path('load_purseseines', views.load_purseseines, name = 'load_purseseines'), 
    path('load_trawlers', views.load_trawlers, name = 'load_trawlers'), 
    path('load_others', views.load_others, name = 'load_others'), 
    path('utils', views.utils, name = 'utils'), 
    path('load_tracks/<str:mmsi>/<str:start>/<str:end>', views.load_tracks, name = 'load_tracks'),
    path('test2', views.test2, name = 'test2'),
    path('anomalies', views.anomalies, name = 'anomalies'),
    path('load_anomalies_day1', views.load_anomalies_day1, name = 'load_anomalies_day1'),
    path('load_anomalies_day2', views.load_anomalies_day2, name = 'load_anomalies_day2'),
    path('load_anomalies_day3', views.load_anomalies_day3, name = 'load_anomalies_day3'),
    path('load_anomalies_day4', views.load_anomalies_day4, name = 'load_anomalies_day4'),
    path('load_anomalies_day6', views.load_anomalies_day6, name = 'load_anomalies_day6'),
    path('sea_traffic', views.sea_traffic, name = 'sea_traffic'),
    path('load_traffic/<str:start>/<str:end>', views.load_traffic, name = 'load_traffic'),
    path('fishing_spots', views.fishing_spots, name = 'fishing_spots'), 
    path('nearby_fishing_spots', views.nearby_fishing_spots, name = 'nearby_fishing_spots'),
    path('fishing_spots_pm', views.fishing_spots_pm, name = 'fishing_spots_pm'),
    path('fishermen', views.fishermen, name = 'fishermen'), 
]