# Generated by Django 3.0.8 on 2021-01-30 05:21

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0002_fixedgear'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.FloatField(null=True)),
                ('timestamp', models.FloatField(null=True)),
                ('distance_f', models.FloatField(null=True)),
                ('distance00', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('course', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('is_fishing', models.FloatField(null=True)),
                ('source', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='PurseSeines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.FloatField(null=True)),
                ('timestamp', models.FloatField(null=True)),
                ('distance_f', models.FloatField(null=True)),
                ('distance00', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('course', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('is_fishing', models.FloatField(null=True)),
                ('source', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Trawlers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.FloatField(null=True)),
                ('timestamp', models.FloatField(null=True)),
                ('distance_f', models.FloatField(null=True)),
                ('distance00', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('course', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('is_fishing', models.FloatField(null=True)),
                ('source', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Trollers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.FloatField(null=True)),
                ('timestamp', models.FloatField(null=True)),
                ('distance_f', models.FloatField(null=True)),
                ('distance00', models.FloatField(null=True)),
                ('speed', models.FloatField(null=True)),
                ('course', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('is_fishing', models.FloatField(null=True)),
                ('source', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
    ]
