# Generated by Django 3.0.8 on 2021-01-30 12:57

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0003_poleline_purseseines_trawlers_trollers'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeVessels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.FloatField()),
                ('flag', models.CharField(max_length=254)),
                ('geartype', models.CharField(max_length=254)),
                ('lat_bin', models.FloatField()),
                ('lon_bin', models.FloatField()),
                ('fishing', models.FloatField()),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('col8', models.CharField(max_length=254)),
                ('col9', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
