# Generated by Django 3.0.8 on 2021-01-30 12:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0004_realtimevessels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtimevessels',
            name='col8',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='col9',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='fishing',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='flag',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='geartype',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='lat_bin',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='lon',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='realtimevessels',
            name='lon_bin',
            field=models.FloatField(null=True),
        ),
    ]
