# Generated by Django 3.0.8 on 2021-01-30 13:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0005_auto_20210130_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='RealTimeVessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmsi', models.FloatField(null=True)),
                ('flag', models.CharField(max_length=254, null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('fishing', models.FloatField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='RealTimeVessels',
        ),
    ]
