# Generated by Django 3.0.8 on 2021-01-31 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0009_auto_20210131_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trajectory',
            old_name='times',
            new_name='time',
        ),
    ]
