# Generated by Django 3.0.8 on 2021-02-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0013_anomaly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomaly',
            name='basedateti',
            field=models.FloatField(null=True),
        ),
    ]
