# Generated by Django 3.0.8 on 2021-02-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0014_auto_20210202_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomaly',
            name='col0',
            field=models.BigIntegerField(null=True),
        ),
    ]
