# Generated by Django 3.0.8 on 2021-02-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0017_auto_20210202_0113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Anchorages',
        ),
        migrations.DeleteModel(
            name='DriftingLonglines',
        ),
        migrations.DeleteModel(
            name='FixedGear',
        ),
        migrations.DeleteModel(
            name='PoleLine',
        ),
        migrations.DeleteModel(
            name='PurseSeines',
        ),
        migrations.DeleteModel(
            name='Trawlers',
        ),
        migrations.DeleteModel(
            name='Trollers',
        ),
    ]
