# Generated by Django 3.0.8 on 2021-02-02 16:36

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0019_anomalyday1'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDay2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unnamed', models.BigIntegerField(null=True)),
                ('mmsi', models.FloatField(null=True)),
                ('datetime', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('sog', models.FloatField(null=True)),
                ('cog', models.FloatField(null=True)),
                ('heading', models.BigIntegerField(null=True)),
                ('vesselname', models.CharField(max_length=254, null=True)),
                ('imo', models.CharField(max_length=254, null=True)),
                ('callsign', models.CharField(max_length=254, null=True)),
                ('vesseltype', models.CharField(max_length=254, null=True)),
                ('status', models.IntegerField(null=True)),
                ('length', models.CharField(max_length=254, null=True)),
                ('width', models.CharField(max_length=254, null=True)),
                ('draft', models.CharField(max_length=254, null=True)),
                ('cargo', models.CharField(max_length=254, null=True)),
                ('transcieve', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyDay3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unnamed', models.BigIntegerField(null=True)),
                ('mmsi', models.FloatField(null=True)),
                ('datetime', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('sog', models.FloatField(null=True)),
                ('cog', models.FloatField(null=True)),
                ('heading', models.BigIntegerField(null=True)),
                ('vesselname', models.CharField(max_length=254, null=True)),
                ('imo', models.CharField(max_length=254, null=True)),
                ('callsign', models.CharField(max_length=254, null=True)),
                ('vesseltype', models.CharField(max_length=254, null=True)),
                ('status', models.IntegerField(null=True)),
                ('length', models.CharField(max_length=254, null=True)),
                ('width', models.CharField(max_length=254, null=True)),
                ('draft', models.CharField(max_length=254, null=True)),
                ('cargo', models.CharField(max_length=254, null=True)),
                ('transcieve', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='AnomalyDay4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unnamed', models.BigIntegerField(null=True)),
                ('mmsi', models.FloatField(null=True)),
                ('datetime', models.FloatField(null=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('sog', models.FloatField(null=True)),
                ('cog', models.FloatField(null=True)),
                ('heading', models.BigIntegerField(null=True)),
                ('vesselname', models.CharField(max_length=254, null=True)),
                ('imo', models.CharField(max_length=254, null=True)),
                ('callsign', models.CharField(max_length=254, null=True)),
                ('vesseltype', models.CharField(max_length=254, null=True)),
                ('status', models.IntegerField(null=True)),
                ('length', models.CharField(max_length=254, null=True)),
                ('width', models.CharField(max_length=254, null=True)),
                ('draft', models.CharField(max_length=254, null=True)),
                ('cargo', models.CharField(max_length=254, null=True)),
                ('transcieve', models.CharField(max_length=254, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(null=True, srid=4326)),
            ],
        ),
    ]
