# Generated by Django 3.0.8 on 2021-02-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0021_anomalyday6'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fishermen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catch_type', models.CharField(max_length=254, null=True)),
                ('work_date', models.DateField(null=True)),
                ('catch_weight', models.IntegerField(null=True)),
            ],
        ),
    ]
